### ISSUE TITLE
不支持iOS啊

### ISSUE THREAD

**Issue by songxiaoliang** [Moussawi7/react-native-controlled-gif#1]
不支持iOS啊  啊啊啊啊啊啊啊啊啊

**Comment by Moussawi7** [comment]
ios pull is more than welcome

**Comment by songxiaoliang** [comment]
Can you support iOS?

**Comment by Moussawi7** [comment]
@songxiaoliang , unfortunately i don't have iOS experience

**Comment by songxiaoliang** [comment]
@Moussawi7 yeah, Fortunately, I implemented iOS.
