### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by b-asaf** [Moussawi7/react-native-controlled-gif#2]
are you going to support iOS devices?

**Comment by cristianonescu** [comment]
@assafb81 did you fnd  any solution for both (android, ios)? I am also looking for a play/pause feature on a gif :(

**Comment by b-asaf** [comment]
@cristianonescu - I used [rn-sprite-sheet](https://www.npmjs.com/package/rn-sprite-sheet) package in the end.

**Comment by cristianonescu** [comment]
@assafb81 you the MVP thank you!! I'm looking for a solution since a week or two ago! Thanks!
